import { Space_Mono } from 'next/font/google'
import './globals.css'

const spaceMono = Space_Mono({ weight:['400',"700"],subsets: ['latin'] })

export const metadata = {
  title: "tip-calculator-app-main",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className} bg-primary-200 antialiased`}>
        {children}
      </body>
    </html>
  );
}
